name: Automatic build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]  # Trigger when a new release is created

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PLATFORM: x86

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Decide version
      shell: bash
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        CURRENT_SHA=$(git rev-parse --short HEAD)
        if [[ $(git rev-list $LATEST_TAG..HEAD --count) -gt 0 ]]; then
          VERSION="${LATEST_TAG}-${CURRENT_SHA}"
        else
          VERSION="${LATEST_TAG}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get Repository Contributors
      shell: bash
      run: |
        CONTRIBUTORS=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/contributors?per_page=100" | jq -r '.[].login' | paste -sd, -)
        echo "CONTRIBUTORS=$CONTRIBUTORS" >> $GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PluginVersion="${{env.VERSION}}" /p:Contributors="${{env.CONTRIBUTORS}}" ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.PLATFORM}}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ILS_Window_Plugin-${{ env.VERSION }}
        path: |
          Release/*.dll
          Release/*.json

  upload_release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'  # Only runs when a release is created

    steps:
    - name: Download Build Artifacts from Build Job
      id: download-artifact
      uses: dawidd6/action-download-artifact@v7
      with:
        run_id: ${{ github.event.workflow_run.id }}
        path: plugin-artifacts

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        tag: ${{ github.ref }}
        file: plugin-artifacts/**/*
        file_glob: true