
name: Publish

on:
  push:
    tags:
      - '*'

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PLATFORM: x86

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Decide version
      shell: bash
      run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Get Repository Contributors
      shell: bash
      run: |
        CONTRIBUTORS=$(curl "https://api.github.com/repos/${{ github.repository }}/contributors?per_page=100" | jq -r '.[].login' | paste -sd, -)
        echo "CONTRIBUTORS=$CONTRIBUTORS" >> $GITHUB_ENV
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PluginVersion="${{env.VERSION}}" /p:Contributors="${{env.CONTRIBUTORS}}" ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.PLATFORM}}

    - name: Zip the build artifacts
      run: |
        powershell -Command Compress-Archive -Path "Release\*.json","Release\*.dll" -DestinationPath ILS_Window_Plugin-${{ env.VERSION }}.zip

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ILS_Window_Plugin-${{ env.VERSION }}.zip
        tag: ${{ github.ref }}
