name: Upload release

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

permissions:
  contents: write

jobs:
  upload_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.release != null }}

    steps:
    - name: Download Build Artifacts from Build Job
      id: download-artifact
      uses: dawidd6/action-download-artifact@v7
      with:
        path: downloads

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        tag: ${{ github.event.release.tag_name }}
        file: downloads/*.zip
        file_glob: true
